# Generated by Django 3.1.7 on 2021-02-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='none', upload_to='uploads/% Y/% m/% d/'),
            preserve_default=False,
        ),
    ]
