# Generated by Django 3.1.7 on 2021-03-02 15:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=100)),
                ('about_me', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('linkedin_link', models.URLField(blank=True, max_length=300)),
            ],
        ),
    ]
