# Generated by Django 3.1.7 on 2021-03-02 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
