# Generated by Django 3.1.7 on 2021-03-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_delete_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='link',
            new_name='project_link',
        ),
        migrations.AddField(
            model_name='project',
            name='article_link',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
