# Generated by Django 3.1.7 on 2021-04-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='subtitle_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='information',
            name='summary',
            field=models.TextField(default='', max_length=300),
        ),
    ]
