# Generated by Django 3.1.7 on 2021-05-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_auto_20210502_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='information',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='information',
            name='twitter_link',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='information',
            name='youtube_link',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
