# Generated by Django 3.1.7 on 2021-05-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_auto_20210502_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='theme',
            field=models.IntegerField(choices=[(2, 'Very Good'), (1, 'Good'), (0, 'Familiar')], default=0),
        ),
    ]
