# Generated by Django 3.1.7 on 2021-05-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_auto_20210503_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='theme',
            field=models.TextField(choices=[(0, 'primary'), (1, 'link'), (2, 'info')], default=0),
        ),
    ]
